### ISSUE TITLE
The bot dies one minute after invoking

### ISSUE THREAD

**Issue by m-anish** [darkenvy/RSS-IRC-NodeBot#1]
This is the traceback on the terminal: 

`(node:18017)` DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 125.23.112.6:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by psiie** [comment]
The bug has been handled. Had to do with the RSS feed being the same IP as this bot. The solution is to use localhost/posts.rss instead of <ipaddress>/posts.rss
